### ISSUE TITLE
An alternative schema

### ISSUE THREAD

**Issue by Pa-miu** [saladtheory/saladtheory.github.io#10]
A salad is a high entropy/homogeneous mixture of bite size solids maximizing ease of "forkability". I refuse to acknowledge the saladness of pizza.

**Comment by Graeme22** [comment]
Counterpoint: Occasionally lettuce leaves are too big to fit in a single bite. By your definition you can move from a non-salad to a salad simply by chopping a single lettuce leaf in half or removing it from the bowl.

**Comment by gmalmquist** [comment]
I often eat pizza with a knife and fork actually
