### ISSUE TITLE
Water Molecule

### ISSUE THREAD

**Issue by potsie13** [saladtheory/saladtheory.github.io#12]
Is a water molecule a salad, as per salad theory?  I want to say yes but other salad theory followers seem to think no.  Probably need a ruling on this.

**Comment by screx** [comment]
I think a water molecule would be a saladoid, a water droplet would then be considered a salad. Maybe this theory depends on the number of discernible discrete parts, under a microscope a single molecule would be a saladoid but with our human eyes it would not be and would just be part of water.

**Comment by gmalmquist** [comment]
I endorse screx's answer
