### ISSUE TITLE
Where does a human cadaver fit on the salad / soup duality?

### ISSUE THREAD

**Issue by ZeroXFFF1** [saladtheory/saladtheory.github.io#16]
In the interests of causing you a mild amount of mental anguish, I wish to inform you that despite the ethical and health problems associated with eating human flesh, humans are still indeed 'edible' and thus counts as both an 'ingredient' or a 'mix of ingredients, depending on if you count the different body parts and organs as separate. Actually, that's potentially a problem with your definition. How do you determine when a mix starts and an ingredient ends? Would the individual plant cells of the salad leaf count together as a salad leaf, or a mix of nearly identical cells of various degrees of structural integrity? The same food would have radically different entropy values depending on how you answered that question, and should you really allow for that to occur? Either way, according to the definition, it fits within your definition of the soup/salad duality, so I'm forcing you to consider human cadaver-derivative ingredients and then despair at falling under my diabolical plot. Mwahahaha!

**Comment by gmalmquist** [comment]
humans are salads (please do not eat human salads)
