### ISSUE TITLE
This is AMAZING but.... I do have proof that I came up with it first :/

### ISSUE THREAD

**Issue by purplekayla13** [saladtheory/saladtheory.github.io#19]
I LOVE this like truly LOVE this. It was actually sent to be by a tinder match not too long ago. And it baffled me that we defined everything the same way and with the same logic - what they say is true great minds do think alike!! Like it is actually UNCANNY that we did it for the EXACT same reason and used the same dictionary definitions and expansion (although I did not get to your math calculations at any point or rendition so you're truly incredible for doing that). But then I decided to check and see which great mind crunched the ideas first.

According to the site records, you published on December 11th, 2018. The screenshot below will show you that I published (and started presenting my revolutionary PowerPoint) on February 24th, 2018. BUT I do wanna say I do think this is INCREDIBLE again - we should collab next time!! I have no quell or request - maybe like a co-authorship vibe, for if/when we decide to really take this baby to the public arena. All the best to you and continue spreading our great work!

<img width="264" alt="Screen Shot 2022-01-17 at 9 39 56 AM" src="https://user-images.githubusercontent.com/68972018/149791367-7a83a508-fe92-482b-9fa5-dafe5dceff52.png">

**Comment by gmalmquist** [comment]
I wrote the original version of this in a Google doc in 2017, so I'm afraid I have you beat! but this is definitely synchronicity 😆 I love that you found this via a tinder match

all the best to you!


![Screenshot_20220206-181450](https://user-images.githubusercontent.com/3391199/152705673-54790875-68fc-4846-83c3-2cac1adfbaf6.png)
