### ISSUE TITLE
Is a glass of water a salad?

### ISSUE THREAD

**Issue by ValarDragon** [saladtheory/saladtheory.github.io#2]
I'm not sure that the classification of a glass of water is clear under salad theory. By the soup-salad duality,
```
We describe this measure as a food’s “soupiness” coefficient, where a food with soupiness=0 contains no exterior liquid, and a food with soupiness=1 contains no solid components 
```
It would appear that it is not a salad, since one would typically not call water "food".

However in the footnotes, it states that:
```
It can be trivially shown that a food with soupiness=1 is indistinguishable from a beverage.
```
Since I would classify water as a bevarage, and not as a food (and by extension not a food with soupiness=1), this shows that the two sets are distinguishable. So is this conclusion right, or am I missing a step of the proof?

Similarly themed question, 
If I have water with ice, does that count as two ingredients? Its the same thing at different temperatures, so if we call water with ice a salad, then our definition of ingredient is also based on temperature. Per section `Merriam Webster 1`, I think we want to avoid such a situation, and then we can't call water with ice a food.

I wonder if we can leverage water with ice not being a food, to also remove more beverages from food status. (like would "food coloring" be an ingredient, its not really edible)

**Comment by phildini** [comment]
I, too, am curious about this, as in Soup-Salad-Sandwich Space water is mapped to (1, 0, 0).

**Comment by gmalmquist** [comment]
This is a great question.

A glass of water _without_ ice is a low-entropy **hyper-salad**. A glass of water _with_ ice may be a full-salad unto itself, but it's borderline (as it's questionable that ice is a different ingredient than water). A glass of mineral water with ice frozen from a different sort of water is a salad.

There's some discussion of ice and water as "food" in Appendix A, in the section on "Coke with Ice".

> Note that we tried for a while to restrict our definition of “salad” to ingredients which were food. Unfortunately, we failed to find a self-consistent definition of food[4] that didn’t simply encompass all edible materials.

I'll add some more clarifying verbiage to the theory.
