### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by sngo2025** [saladtheory/saladtheory.github.io#25]
First: deep dish pizza is a soup (equivalent to bread bowl French onion soup)
Second: water in ice is a soup (not a salad)
Third: pizza is a open face sandwich (how could it even be a salad like woah)

Drizzle vs Drench Theory: if a group of things is drizzled (like a dressing) to the point that it is coated then it is salad but if it is drenched or covered in liquid then it it a soup.

I've said my peace.

**Comment by gmalmquist** [comment]
I have had plenty of salads in which viscous dressing would be more accurately described as "globbed" onto the salad, that then required tossing. No drizzling involved.

That put aside, 1st & 2nd are addressed with Theorem 1.1, sandwiches are addressed under the "Well-Mixed" subheading.
